# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /
title: Thang Nguyen
author: Chris Turner
description: Personal Website
avatar: profile.png
email: yourname@email.com
github: nguyent
twitter:
linkedin:
google_analytics: